### ISSUE TITLE
Cannot Run createODB

### ISSUE THREAD

**Issue by AmyMcCall** [u-anurag/vfo#12]
u-anurag,

I updated my program (which I was running in Openseespy v. 3.3.0.1) to use the vfo function instead of the postprocessing.get_Rendering commands. I am using vfo.createODB but was getting the error shown in the attached figure (createODBError). One of the variables read in were the number of modes, in this case there are 8. I played around with this number and was finally able to get vfo.createODB to work by using 3 modes instead of 8. Why doesn't this vfo command work with the actual number of modes as it used to with the postprocessing.get_Rendering command in the older version? This may be an issue with the openSees commands since it is getting hung up on ops.eigen(Nmodes+1).

Amy
<img width="293" alt="createODBError" src="https://github.com/u-anurag/vfo/assets/99770560/752cf7df-3caa-422c-bf68-df6ce6495af4">

<img width="577" alt="vfocreateODB" src="https://github.com/u-anurag/vfo/assets/99770560/f3f2a2fb-62f8-4a19-8e38-6573c0e62cd7">

**Comment by u-anurag** [comment]
Hi Amy,

The createODB function uses the default eigenvalue solver which has been problematic in the updated OpenSees. For now, you can change the solver to fullGenLapack to make it work.

**Comment by mhscott** [comment]
@u-anurag Please provide a MWE showing how the default eigen solver is problematic now but was not problematic in a previous version of OpenSees. This is the first I've heard of the default eigen solver presenting _new_ problems.

**Comment by u-anurag** [comment]
@mhscott my comment was purely based on the discussion I saw on the Facebook group. I'll run my models with the updated OpenSees to see if I get the same behavior. 
@AmyMcCall did it work with the fullGenLapack solver?

**Comment by AmyMcCall** [comment]
@mhscott I was already running the fullGenLapack when I directly called the eigen function (see attached image. Also note, I could not get the eigen function to run for all modes without the fullGenLapack in the older version of Openseespy), but I did not include it when I called the createODB function (which later calls the eigen function, see my code in the attached image). The difference now is that I can't run the createODB with all modes included, where I could in the previous version of Openseespy. Should I include fullGenLapack in the createODB function like this: vfo.createODB(FileLoc, EigenLCName, numModes, '-fullGenLapack')?

<img width="401" alt="fullGenLapack" src="https://github.com/u-anurag/vfo/assets/99770560/9fc0c2e9-6d62-4127-acf0-153b5d637ff5">

**Comment by mhscott** [comment]
@AmyMcCall I am not familiar with how `vfo` interacts with the core OpenSees, so I will leave that to @u-anurag. Also, I am not aware of any new issues with the `eigen` command in OpenSees.

**Comment by u-anurag** [comment]
@AmyMcCall Would you mind sharing the script so I can see what is happening?

**Comment by AmyMcCall** [comment]
@u-anurag, the script is pretty complex with several sub-routines and sub-folders. Is there a way I can get you the folder and I can step you through which file to open and run?

**Comment by AmyMcCall** [comment]
I am happy to schedule a meeting. What works for you?

**Comment by u-anurag** [comment]
I am available at 12:30 pm (pacific time) tomorrow. Let's take this conversation to email. Send me an invite on iitg.anurag@gmail.com.
