### ISSUE TITLE
plot_eleHysteresis

### ISSUE THREAD

**Issue by Kageyama96** [u-anurag/vfo#14]
I am trying to plot element hysteresis, but the command is asking for monitoring group. However I don't find syntax asking for  monitor Group Name.

**Comment by u-anurag** [comment]
`plot_eleHysteresis` command is not set up properly. It is not even available in the documentation. How did you find it? I didn't find a lot of demand for it so never fully set it up.

**Comment by Kageyama96** [comment]
I reviewed the VFO package and discovered the method for plotting hysteresis. I'm particularly interested in the hysteresis member. The model is constructed in Tcl, and I'm currently exploring more efficient methods for post-processing. Do you have any suggestions on how I can leverage the existing method?

**Comment by u-anurag** [comment]
It will be easier to integrate this method with OpenSeesPy than Tcl. I had a working code with this method but never finished integrating it. For now, you could switch to OpenSeesPy and use `eleResponse` command locally to get the data for plotting.

**Comment by Kageyama96** [comment]
Thank you very much, I will look into this.
