### ISSUE TITLE
vfo error

### ISSUE THREAD

**Issue by rameshadhikari07** [u-anurag/vfo#15]
![error message](https://github.com/u-anurag/vfo/assets/53815413/e2419c86-ecf8-4dae-afef-03aa17c0a32d)
![graphical interface](https://github.com/u-anurag/vfo/assets/53815413/cdaa747f-2d9c-4a37-8005-c643845fca7a)

I am getting the following error while plotting the deformed shape for my Pushover analysis. I get ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Also, the slider shows a negative time step. Is it normal to have a negative time step value?

However, I can view the model. What could be the problem here?

Thank you.

**Comment by u-anurag** [comment]
For a pushover analysis, the slider shows the analysis load factor. For a time-history analysis, it will show the time step. 

I am not sure what the problem is. Could you share the ODB folder so I can take a look? Upload on your GitHub account and share the link.

**Comment by rameshadhikari07** [comment]
https://github.com/rameshadhikari07/vfoPushover/tree/main/1MRF_ODB
I realized that one of my element tags had 7 digits. I changed that, and I could see the deformed model. However, the amount of deformation does not change even when I drag the slider. Furthermore, the slider shows the load factor, is it normal to get a negative load factor?

Now, I am getting a new issue while plotting the mode shapes. I get the following error:
![image](https://github.com/u-anurag/vfo/assets/53815413/221563c1-77da-44a1-abce-e08676d58ced)
(I created an ODB as **_vfo.createODB(model='1MRF', Nmodes=10, loadcase='Pushover')_**)

However, I successfully ran an Eigenvalue analysis in Opensees using the _**eigen()**_ function.

**Comment by u-anurag** [comment]
The error shows the eigen analysis failed. 

The negative load factor in pushover analysis is common and depends on the model.
