### ISSUE TITLE
No node displacement from loadcase was found

### ISSUE THREAD

**Issue by allenyoga** [u-anurag/vfo#16]
Hello, 

I have a model in OpenSees and I wanted to plot the deformed shape using vfo. However, it seems like 'vfo' couldn't access the subfolder, 'loadcase', from OBD file on my computer: 

```
File "/Users/allenyogalee/anaconda3/envs/OpenSees/lib/python3.8/site-packages/vfo/vfo.py", line 609, in plot_deformedshape
    raise Exception(">>>> VFO ERROR: No node displacements from loadcase was found in "+model+"_ODB. Exiting 'plot_deformedshape()' now. <<<<")
Exception: >>>> VFO ERROR: No node displacements from loadcase was found in solar_panel_ODB. Exiting 'plot_deformedshape()' now. <<<<
```

There was no problem plotting modeshapes, so I don't think it's an access file authorization issue.

It's my computer's problem since the same code worked on my friend's computer. 

It would be greatly appreciated if anyone could assist me with this issue.

**Comment by allenyoga** [comment]
Hi, 

I kind of resolved the issue above by only running the script create deformshape/animation script directly in the python interactive shell: 

`>>> import vfo.vfo as vfo
>>> ani = vfo.animate_deformedshape(model="solar_panel_large",loadcase="wind",scale=5,speedup=1,contour="none",setview="3D",line_width=1,node_for_th=None,node_dof=3 ,gifname='new')
Reading structure data from solar_panel_large_ODB.
Reading loadcase 'wind' data from solar_panel_large_ODB.
calculating maximum node deflections
Creating animation gif/movie file. On-screen updating may seem choppy/slow. Please don't close the window.
Movie/Gif file is saved.`

However, one other issue came up. The file wasn't saved since it's temporarily stored in the memory. If I 'exit()' the python shell the memory will be wiped out. 

Is there a way to save it? I read through the source code of yours but hasn't figured out a way to use imageio. 

Any help would be greatly appreciated. Thanks.

**Comment by u-anurag** [comment]
I am not sure why it wouldn't be saved. Did you check the folder? If it is a permission issue on your computer, then you'll have to figure it out.
