### ISSUE TITLE
Save my vfo or geometry 

### ISSUE THREAD

**Issue by hszhang1** [u-anurag/vfo#17]
Hi I have one question about vfo or model geometry. Can I know if I can save my model geometry or vfo as obj or stl or ply file?

Thanks!

**Comment by u-anurag** [comment]
@hszhang1 Hi, vfo doesn't save the geometry to any other format. What are you trying to export it to?

**Comment by hszhang1** [comment]
Hi,

I'm trying to work on a little of CFD so I want to see if I can export my openseespy geometry to STL file.

**Comment by u-anurag** [comment]
vfo doesn't have this functionality.
