### ISSUE TITLE
Error importing vfo on Mac M2

### ISSUE THREAD

**Issue by Omar-A-M** [u-anurag/vfo#18]
Hey Anurag,

I use pip install vfo to install vfo but whenever I use import vfo.vfo i get the following error:
ModuleNotFoundError: No module named 'vfo.vfo'; 'vfo' is not a package

I try running "pip list | grep vfo" I get vfo 0.0.17. 

Any insights what might be the issue here? 
Thanks in advance

**Comment by u-anurag** [comment]
Hi Omar,

I think this is an issue with Mac installation. I don't have a Mac book so can't dig deeper, but, a quick google search showed me that it is a common issue. You could try to use Anaconda Python for Mac for a better package management.

**Comment by Omar-A-M** [comment]
Thank you Anurag for your prompt response. I will try to do that and see how it goes.

**Comment by Omar-A-M** [comment]
Hey Anurag, 
I have tried using Anaconda but still getting the same error. I am able to import openseespy but not vfo. Any guide on where might the issue be?

**Comment by u-anurag** [comment]
Make sure `openseespy` and `vfo` are in the same conda environment. It is difficult to know what is happening with the Mac installation. Make sure you import vfo as 

`import vfo.vfo as vfo`

**Comment by Omar-A-M** [comment]
They are in the same environment and I do import vfo.vfo as vfo. The first picture is a simple script to get the directories of the imports and the second picture shows the output. Maybe it will help.

![image](https://github.com/u-anurag/vfo/assets/155535937/b32cd10c-8e60-46ec-bea6-4da2744159af)

![image](https://github.com/u-anurag/vfo/assets/155535937/9204b586-15fc-4e22-9a15-f2282435297f)

**Comment by u-anurag** [comment]
The file path for `vfo` should partly match the path of `openseespy`. The image shows that your machine is looking for `vfo` in `~/Documents/opensees/Paper1/Model_10/vfo.py`.

The package should be installed in location `/opt/miniconda3/envs/op_env/lib/python3.10/site-packages/vfo/`.

Are you sure you installed the package in your conda environment using `pip install vfo`?

**Comment by Omar-A-M** [comment]
Yes I have installed it on the same env, as shown in picture:

![image](https://github.com/u-anurag/vfo/assets/155535937/747246b4-db0b-45fb-8593-116a7faa0131)

**Comment by u-anurag** [comment]
Can't say what the issue is. I am still puzzled on why it is showing a file `vfo.py` in your working directory. Make sure you don't have any file with the name `vfo.py` in your working folder.

**Comment by Omar-A-M** [comment]
Hey Anurag, thank you so much for your suggestions. Indeed there was a file named vfo.py in the directory and after removing it, everything works fine.
