### ISSUE TITLE
Errors plotting OBD file

### ISSUE THREAD

**Issue by Omar-A-M** [u-anurag/vfo#19]
Hey Anurag,

I have been trying to use the new update which allows plotting models with long node and element tags. But I face the following errors while plotting the ODB file on vMachine:

File "c:\Users\user\Desktop\Vis\v.py", line 4, in
vfo.plot_model(model='Pushover4_X_16mm', line_width=1)
File "C:\Users\user\Desktop\Vis.venv\Lib\site-packages\vfo\vfo.py", line 483, in plot_model
mesh_original, mesh_lines_original, vertices, nodeTags = _get_modelDisplay(nodeArray, elementArray, eleClassTags)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Desktop\Vis.venv\Lib\site-packages\vfo\vfo.py", line 350, in _get_modelDisplay
lines = _getPV_2NodeELements(elementArray)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Desktop\Vis.venv\Lib\site-packages\vfo\vfo.py", line 292, in _getPV_2NodeELements
tempArray = np.array([2, _getNodeIndex(ii[1]), _getNodeIndex(ii[2])])
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\user\Desktop\Vis.venv\Lib\site-packages\vfo\vfo.py", line 271, in _getNodeIndex
return int(nodeIndex)
^^^^^^^^^^^^^^
TypeError: only length-1 arrays can be converted to Python scalars

The ODB file is on the link bellow:
https://drive.google.com/drive/folders/1DSOnwwWhOKrknjdEqtEfjkkv5emTEd63?usp=sharing

Thank you in advance

**Comment by u-anurag** [comment]
The `Nodes.out` file has multiple nodes with identical tags. Which version of `vfo` are you using? Make sure you are using 0.0.17.

**Comment by Omar-A-M** [comment]
I am still facing the same issue. When I plot the model it works but when I try to plot the ODB file I get that error. VFO version is 0.0.17.

**Comment by u-anurag** [comment]
Okay, let me look into it.

**Comment by u-anurag** [comment]
@Omar-A-M can you share the latest ODB files? The ones on G-drive folder are from an older vfo version.

**Comment by u-anurag** [comment]
Make sure you re-create the output database with the latest version of vfo for the command to work.

**Comment by Omar-A-M** [comment]
Hey Anurag, 

Thank you for your reply. I have updated the ODB file but still facing the same issue.

Link to ODB: https://drive.google.com/drive/folders/1X5raS9ONsCSvS2UxLulMiTyJGdd3x7Vt?usp=sharing

**Comment by u-anurag** [comment]
It works fine for me, 

vfo version - 0.0.18

Just these 2 commands :

`import vfo.vfo as vfo`
`vfo.plot_model(model="Results_Wind_ULS_Y")`

![image](https://github.com/user-attachments/assets/4dcb6413-6ddb-469c-a301-8f4f59e7b819)

**Comment by u-anurag** [comment]
Here is the deformed shape, 

command:  `vfo.plot_deformedshape(model="Results_Wind_ULS_Y", loadcase="Results_Wind_ULS_Y", contour="y", scale=50)`

![image](https://github.com/user-attachments/assets/4cbfcd70-5f35-401a-8635-71190e0e55d1)

**Comment by Omar-A-M** [comment]
Hey Dr. Anurag,

I have updated vfo and now everything is working as it should. Thank you.

I have another question, I will use plots from vfo in my paper. How should I reference vfo?

**Comment by u-anurag** [comment]
I am glad it is working. You can cite this `vfo` as,

Upadhyay, A. vfo (Visualization For OpenSees) (Version 0.0.18) [Computer software]. https://github.com/u-anurag/vfo
