### ISSUE TITLE
Tetrahedrals drawn as plates/shells

### ISSUE THREAD

**Issue by mhscott** [u-anurag/vfo#2]
You can use the eleType command to determine if a 3D element with four nodes is a plate/shell or tetrahedron
![image](https://user-images.githubusercontent.com/13142652/143784159-eb3843a9-beab-400f-ae5a-215ff5e95f7f.png)

**Comment by u-anurag** [comment]
Thank you for the hint, Dr. Scott! This seems a better check than what I was working on. I'll fix this soon.

**Comment by u-anurag** [comment]
I have fixed the issue in the latest release.
