### ISSUE TITLE
getting error with vfo.plot_model(elementgroups=[[numpyArr1.astype(int), numpyArr2.astype(int), numpyArr3.astype(int)],["red","blue", "yellow"]])

### ISSUE THREAD

**Issue by bahugunaashish** [u-anurag/vfo#20]
If I am just entering the command with numpyArr1.astype(int) it is **executing ok**. 
If I am entering the command with numpyArr1.astype(int) and numpyArr2.astype(int)  it is **executing ok**. 

But For some reason, I am getting an error when I am adding numpyArr3.astype(int) into the command.

  F**ile ~\.conda\envs\py39\lib\site-packages\vfo\vfo.py:508 in plot_model
    thisgroup_elementArray[ii] = elementArray[int(i)]**

**TypeError: only length-1 arrays can be converted to Python scalars**

For your reference all three arrays are numpy array defined in the same way.

**Comment by u-anurag** [comment]
The input has to be a list and NOT an array. Could you try that?

**Comment by u-anurag** [comment]
Let me know if the issue still persists.
